# Generated by Django 5.2.3 on 2025-06-10 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=40, verbose_name='نام مدیر')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن مدرسه ')),
                ('school_address', models.TextField(verbose_name='آدرس مدرسه')),
                ('roubica', models.URLField(verbose_name='لینک کانال یا راه ارتباطی روبیکا شما')),
                ('instagram', models.URLField(verbose_name='لینک کانال یا راه ارتباطی اینستاگرام شما')),
                ('soroosh', models.URLField(verbose_name='لینک کانال یا راه ارتباطی سروش شما')),
            ],
            options={
                'verbose_name': 'فوتر سایت',
                'verbose_name_plural': 'فوتر سایت',
            },
        ),
        migrations.CreateModel(
            name='LimitContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('date_set', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceUserForSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pardakht_shode', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت شده')),
                ('baghimonde', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ باقی مانده')),
                ('user_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی کاربر')),
                ('user_phone', models.CharField(max_length=12, verbose_name='شماره کاربر')),
                ('price_check', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت چک اول')),
                ('check_serial', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال چک')),
                ('check_date', models.CharField(blank=True, help_text='مثل 1402/02/02', max_length=20, null=True, verbose_name='تاریخ چک')),
                ('price_check2', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت چک دوم')),
                ('check_serial2', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال چک دوم')),
                ('check_date2', models.CharField(blank=True, help_text='مثل 1402/02/02', max_length=20, null=True, verbose_name='تاریخ چک')),
                ('price_check3', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت چک سوم')),
                ('check_serial3', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال چک سوم')),
                ('check_date3', models.CharField(blank=True, help_text='مثل 1402/02/02', max_length=20, null=True, verbose_name='تاریخ چک')),
            ],
            options={
                'verbose_name': 'چک های دانش آموزان',
                'verbose_name_plural': 'چک های دانش آموزان',
            },
        ),
        migrations.CreateModel(
            name='SetPriceForSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_rahnamaee', models.PositiveIntegerField(help_text='قیمت را به تومان و بدون علائم نگارشی وارد کنید ', verbose_name='شهریه مقطع راهنمایی')),
                ('price_for_dabirestan', models.PositiveIntegerField(help_text='قیمت را به تومان و بدون علائم نگارشی وارد کنید ', verbose_name='شهریه مقطع دبیرستان')),
            ],
            options={
                'verbose_name': 'تنظیم شهریه مدرسه',
                'verbose_name_plural': 'تنظیم شهریه مدرسه',
            },
        ),
        migrations.CreateModel(
            name='WelcomeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن خوش آمد گویی صفحه ثبت نام')),
            ],
            options={
                'verbose_name': 'متن صفحه ثبت نام',
                'verbose_name_plural': 'متن\u200cهای صفحه ثبت نام',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن ثبت نام')),
                ('role', models.CharField(choices=[('student', 'دانش\u200cآموز'), ('teacher', 'معلم'), ('admin', 'مدیر')], default='student', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کدفعلی OTP')),
                ('otp_token', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='توکن OTP')),
                ('otp_expire_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای OTP')),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای OTP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('user_birthday_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد (رشته)')),
                ('section', models.CharField(blank=True, choices=[('rahnamii', 'متوسطه اول'), ('dabirestan', 'متوسطه دوم')], max_length=30, null=True, verbose_name='مقطع تحصیلی')),
                ('grade', models.CharField(blank=True, choices=[('haftom', 'هفتم'), ('hashtom', 'هشتم'), ('nohom', 'نهم'), ('dahom', 'دهم'), ('yazdahom', 'یازدهم'), ('davazdahom', 'دوازدهم')], max_length=30, null=True, verbose_name='پایه تحصیلی')),
                ('field_of_study', models.CharField(blank=True, choices=[('riazi', 'ریاضی'), ('tajrobi', 'تجربی'), ('ensani', 'انسانی')], max_length=30, null=True, verbose_name='رشته تحصیلی')),
                ('father_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام پدر')),
                ('mother_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام و نام خانوادگی مادر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس منزل')),
                ('father_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن پدر')),
                ('mother_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره مادر')),
                ('father_job', models.CharField(blank=True, max_length=40, null=True, verbose_name='شغل پدر')),
                ('mother_job', models.CharField(blank=True, max_length=40, null=True, verbose_name='شغل مادر')),
                ('father_education', models.CharField(blank=True, max_length=50, null=True, verbose_name='تحصیلات پدر')),
                ('mother_education', models.CharField(blank=True, max_length=50, null=True, verbose_name='تحصیلات مادر')),
                ('job_father_address', models.TextField(blank=True, null=True, verbose_name='آدرس شغل پدر')),
                ('job_mother_address', models.TextField(blank=True, null=True, verbose_name='آدرس شغل مادر')),
                ('student_code_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی دانش آموز')),
                ('father_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه پدر')),
                ('mother_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه مادر')),
                ('sibling_education', models.TextField(blank=True, null=True, verbose_name='تحصیلات خواهر یا برادر')),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='', verbose_name='پروفایل')),
                ('super_student_user', models.BooleanField(default=False, verbose_name='قابلیت پرداخت و ثبت نام')),
                ('is_information_submited', models.BooleanField(default=False, verbose_name='کاربر اطلاعات شخصی خود را کامل کرده است')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانش آموز',
                'verbose_name_plural': 'اطلاعات کاربری دانش آموزان',
            },
        ),
    ]
