# Generated by Django 5.2.3 on 2025-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='basic_info',
            field=models.BooleanField(default=False, verbose_name='آیا اطلاعات اولیه تکمیل شده است ؟'),
        ),
    ]
