# Generated by Django 5.0.6 on 2024-05-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelcomRegister',
            new_name='WelcomeRegister',
        ),
    ]
