# Generated by Django 5.2.3 on 2025-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_studentprofile_basic_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
