# Generated by Django 5.0.6 on 2024-05-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_welcomregister_welcomeregister'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomeregister',
            options={'verbose_name': 'متن صفحه ثبت نام', 'verbose_name_plural': 'متن صفحه ثبت نام '},
        ),
        migrations.AlterField(
            model_name='welcomeregister',
            name='text',
            field=models.TextField(verbose_name='متن خوش آمد گویی صفحه ثبت نام'),
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_date', models.DateField()),
                ('section', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=30, null=True)),
                ('father_name', models.CharField(blank=True, max_length=40, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('father_job', models.CharField(blank=True, max_length=40, null=True)),
                ('mother_job', models.CharField(blank=True, max_length=40, null=True)),
                ('father_education', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_education', models.CharField(blank=True, max_length=50, null=True)),
                ('job_father_address', models.TextField(blank=True, null=True)),
                ('job_mother_address', models.TextField(blank=True, null=True)),
                ('student_code_id', models.CharField(blank=True, max_length=10, null=True)),
                ('father_serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sibling_education', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(upload_to='')),
                ('super_student_user', models.BooleanField(default=False, verbose_name='قابلیت پرداخت و ثبت نام')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
