# Generated by Django 5.2.3 on 2025-06-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_year_gpa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معدل سال قبل'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرسه سال قبل'),
        ),
    ]
