# Generated by Django 5.2.3 on 2025-06-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_studentprofile_last_year_gpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_token',
        ),
    ]
