# Generated by Django 5.0.6 on 2024-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userstudent_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudent',
            name='mother_phone',
        ),
        migrations.RemoveField(
            model_name='userstudent',
            name='password2',
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس منزل'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='father_education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تحصیلات پدر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='father_job',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='شغل پدر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='father_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='father_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن پدر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='father_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه پدر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='grade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='job_father_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس شغل پدر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='job_mother_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس شغل مادر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='mother_education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تحصیلات مادر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='mother_job',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='شغل مادر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='mother_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام و نام خانوادگی مادر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='mother_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه مادر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='password1',
            field=models.CharField(max_length=100, verbose_name='رمز ورود'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن ثبت نام'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='profile',
            field=models.ImageField(default='static_files/profile/22_Profile.jpg', upload_to='media', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='section',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='sibling_education',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='student_code_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی دانش آموز'),
        ),
    ]
