# Generated by Django 5.2.3 on 2025-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_for_signup',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='هدف ثبت نام : '),
        ),
    ]
