# Generated by Django 5.0.6 on 2024-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userstudent_mother_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره مادر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='birthday_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='sibling_education',
            field=models.TextField(blank=True, null=True, verbose_name='تحصیلات خواهر یا برادر'),
        ),
    ]
