# Generated by Django 5.0.6 on 2024-05-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userstudent_mother_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstudent',
            options={'verbose_name': 'دانش آموز مورد نظر', 'verbose_name_plural': 'اطلاعات کاربری دانش آموزان'},
        ),
        migrations.RemoveField(
            model_name='userstudent',
            name='password1',
        ),
    ]
