# Generated by Django 5.2.3 on 2025-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_studentprofile_target_for_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='تاریخ تولد اولیه'),
        ),
    ]
