# Generated by Django 5.2.3 on 2025-06-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_studentprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user_birthday_date',
        ),
    ]
