# Generated by Django 5.0.6 on 2024-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstudent',
            options={'verbose_name': 'دانش آموز', 'verbose_name_plural': 'اطلاعات کاربری دانش آموزان'},
        ),
        migrations.AlterModelOptions(
            name='welcomeregister',
            options={'verbose_name': 'متن صفحه ثبت نام', 'verbose_name_plural': 'متن\u200cهای صفحه ثبت نام'},
        ),
        migrations.AddField(
            model_name='userstudent',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='grade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='profile',
            field=models.ImageField(default='static_files/profile/22_Profile.jpg', upload_to='profiles/', verbose_name='پروفایل'),
        ),
    ]
