# Generated by Django 5.0.6 on 2024-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='username',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
    ]
