# Generated by Django 5.0.6 on 2024-05-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userstudent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudent',
            name='profile',
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='آدرس ایمیل'),
        ),
    ]
