# Generated by Django 5.0.6 on 2024-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_userstudent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='password1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userstudent',
            name='password2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
