# Generated by Django 5.0.6 on 2024-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userstudent_password1_userstudent_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
