# Generated by Django 5.0.6 on 2024-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_userstudent_birthday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=4)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعتبارسنجی کاربر',
                'verbose_name_plural': 'اعتبارسنجی کاربران',
            },
        ),
    ]
