# Generated by Django 5.0.6 on 2024-06-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_otp_last_request_time_otp_request_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='last_request_time',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='request_count',
        ),
    ]
