# Generated by Django 5.0.6 on 2024-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_otp_id_alter_otp_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='پروفایل'),
        ),
    ]
