# Generated by Django 5.0.6 on 2024-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_userstudent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='field_of_study',
            field=models.CharField(blank=True, choices=[('tajrobi', 'تجربی'), ('riazi', 'ریاضی و فیزیک'), ('ensani', 'انسانی'), ('honarestan', 'هنرستان'), ('noOne', 'هیچکدام(پایه نهم هستم)')], max_length=30, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='grade',
            field=models.CharField(blank=True, choices=[('nohom', 'نهم'), ('dahom', 'دهم'), ('yazdahom', 'یازدهم'), ('davazdahom', 'دوازدهم')], max_length=30, null=True, verbose_name='پایه تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='section',
            field=models.CharField(blank=True, choices=[('dabirestan', 'دبیرستان دوره دوم'), ('rahnamii', 'دبیرستان دوره اول'), ('dabestan', 'دبستان')], max_length=30, null=True, verbose_name='مقطع تحصیلی'),
        ),
    ]
