# Generated by Django 5.0.6 on 2024-06-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_userstudent_field_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=30)),
                ('extra_information', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='username',
            field=models.CharField(max_length=30, verbose_name='نام کاربری'),
        ),
    ]
