# Generated by Django 5.0.6 on 2024-06-05 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_contactus_alter_userstudent_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ارتباط کاربر ها با مدیرمدرسه', 'verbose_name_plural': 'ارتباط کاربر ها با مدیرمدرسه'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='user_student_connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_to_us', to='account.userstudent'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='extra_information',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اطلاعات بیشتر از کاربر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس کاربر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
