# Generated by Django 5.0.6 on 2024-06-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='extra_information',
        ),
    ]
