# Generated by Django 5.0.6 on 2024-06-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_contactus_extra_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('date_set', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='extra_information',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اطلاعات بیشتر از کاربر'),
        ),
    ]
