# Generated by Django 5.0.6 on 2024-06-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_limitcontactus_contactus_extra_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitcontactus',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
