# Generated by Django 5.0.6 on 2024-06-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_rename_phone_limitcontactus_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
