# Generated by Django 5.0.6 on 2024-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_delete_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='is_information_submited',
            field=models.BooleanField(default=False, verbose_name='کاربر اطلاعات شخصی خود را کامل کرده است ؟ '),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='field_of_study',
            field=models.CharField(blank=True, choices=[('tajrobi', 'ریاضی'), ('riazi', 'تجربی'), ('ensani', 'انسانی')], max_length=30, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='section',
            field=models.CharField(blank=True, choices=[('dabirestan', 'متوسطه اول'), ('rahnamii', 'متوسطه دوم')], max_length=30, null=True, verbose_name='مقطع تحصیلی'),
        ),
    ]
