# Generated by Django 5.0.6 on 2024-06-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_userstudent_field_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=40, verbose_name='نام مدیر')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن مدرسه ')),
                ('school_address', models.TextField(verbose_name='آدرس مدرسه')),
                ('roubica', models.URLField(verbose_name='لینک کانال یا راه ارتباطی روبیکا شما')),
                ('instagram', models.URLField(verbose_name='لینک کانال یا راه ارتباطی اینستاگرام شما')),
                ('soroosh', models.URLField(verbose_name='لینک کانال یا راه ارتباطی سروش شما')),
            ],
        ),
    ]
