# Generated by Django 5.0.6 on 2024-06-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'فوتر سایت', 'verbose_name_plural': 'فوتر سایت'},
        ),
    ]
