# Generated by Django 5.0.6 on 2024-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_footer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل'),
        ),
    ]
