# Generated by Django 5.0.6 on 2024-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_userstudent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='user_birthday_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
