# Generated by Django 5.0.6 on 2024-06-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_userstudent_user_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='grade',
            field=models.CharField(blank=True, choices=[('haftom', 'هفتم'), ('hashtom', 'هشتم'), ('nohom', 'نهم'), ('dahom', 'دهم'), ('yazdahom', 'یازدهم'), ('davazdahom', 'دوازدهم')], max_length=30, null=True, verbose_name='پایه تحصیلی'),
        ),
    ]
