# Generated by Django 5.0.6 on 2024-06-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_setpriceforschool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setpriceforschool',
            options={'verbose_name': 'تنظیم شهریه مدرسه', 'verbose_name_plural': 'تنظیم شهریه مدرسه'},
        ),
        migrations.AlterField(
            model_name='setpriceforschool',
            name='price_for_dabirestan',
            field=models.PositiveIntegerField(help_text='قیمت را به تومان و بدون علائم نگارشی وارد کنید ', verbose_name='شهریه مقطع دبیرستان'),
        ),
        migrations.AlterField(
            model_name='setpriceforschool',
            name='price_for_rahnamaee',
            field=models.PositiveIntegerField(help_text='قیمت را به تومان و بدون علائم نگارشی وارد کنید ', verbose_name='شهریه مقطع راهنمایی'),
        ),
    ]
