# Generated by Django 5.0.6 on 2024-06-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_setpriceforschool_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUserForSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pardakht_shode', models.PositiveIntegerField(verbose_name='مبلغ پرداخت شده')),
                ('baghimonde', models.PositiveIntegerField(verbose_name='مبلغ باقی مانده')),
                ('check_serial', models.CharField(max_length=20, verbose_name='شماره سریال چک')),
                ('check_date', models.CharField(help_text='مثل 1402/02/02', max_length=20, verbose_name='تاریخ چک')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربر')),
                ('user_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره کاربر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_price', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
