# Generated by Django 5.0.6 on 2024-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_priceuserforschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceuserforschool',
            name='check_date2',
            field=models.CharField(blank=True, help_text='مثل 1402/02/02', max_length=20, null=True, verbose_name='تاریخ چک'),
        ),
        migrations.AddField(
            model_name='priceuserforschool',
            name='check_date3',
            field=models.CharField(blank=True, help_text='مثل 1402/02/02', max_length=20, null=True, verbose_name='تاریخ چک'),
        ),
        migrations.AddField(
            model_name='priceuserforschool',
            name='check_serial2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال چک دوم'),
        ),
        migrations.AddField(
            model_name='priceuserforschool',
            name='check_serial3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال چک سوم'),
        ),
        migrations.AddField(
            model_name='priceuserforschool',
            name='price_check',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceuserforschool',
            name='price_check2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceuserforschool',
            name='price_check3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='check_serial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال چک'),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی کاربر'),
        ),
    ]
