# Generated by Django 5.0.6 on 2024-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_priceuserforschool_check_date2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceuserforschool',
            name='baghimonde',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ باقی مانده'),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='pardakht_shode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='price_check',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=' قیمت چک اول'),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='price_check2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت چک دوم'),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='price_check3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت چک سوم'),
        ),
    ]
