# Generated by Django 5.0.6 on 2024-06-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_priceuserforschool_baghimonde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceuserforschool',
            name='user',
        ),
    ]
