# Generated by Django 5.0.6 on 2024-06-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_remove_priceuserforschool_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceuserforschool',
            options={'verbose_name': 'چک های دانش آموزان', 'verbose_name_plural': 'چک های دانش اموزان'},
        ),
    ]
