# Generated by Django 5.0.6 on 2024-06-16 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_priceuserforschool_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceuserforschool',
            name='check_date',
            field=models.CharField(blank=True, help_text='مثل 1402/02/02', max_length=20, null=True, verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی کاربر'),
        ),
        migrations.AlterField(
            model_name='priceuserforschool',
            name='user_phone',
            field=models.CharField(max_length=12, verbose_name='شماره کاربر'),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL, verbose_name='ارتباط با'),
        ),
    ]
