# Generated by Django 5.2.3 on 2025-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, verbose_name='نام دوره')),
                ('price', models.IntegerField(help_text='حتما قیمت دوره را به تومان و بدون هیچ علائم نگارشی اضافه ای وارد کنید ', verbose_name='قیمت دوره')),
                ('teacher', models.CharField(help_text='فقط اسم و فامیل استاد را بنویسید نیاز به نوشتن کلمه استاد قبل از اسم اساتید نیست ', max_length=30, verbose_name='استاد دوره')),
                ('date_starter', models.DateField(help_text='اگر روز شروع خاصی مد نظرتون نیست یا شروع خاصی ندارد تاریخ امروز را وارد کنید', verbose_name='روز شروع دوره')),
                ('banner', models.FileField(blank=True, null=True, upload_to='course_banners/', verbose_name='عکس دوره')),
                ('course_type', models.CharField(choices=[('book', 'کتاب'), ('teacher', 'آموزش')], max_length=30, verbose_name='نوع دوره')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('off', models.IntegerField(blank=True, help_text='لطفا فقط عدد وارد کنید،لطفا عدد وارد شده بین 1 تا 100 باشد', null=True, verbose_name='درصد تخفیف')),
                ('price_with_off', models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف ')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
    ]
