# Generated by Django 5.0.6 on 2024-06-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, verbose_name='نام دوره')),
                ('price', models.CharField(max_length=20, verbose_name='قیمت دوره')),
                ('teacher', models.CharField(max_length=30, verbose_name='استاد دوره')),
                ('date_starter', models.DateField(verbose_name='روز شروع دوره')),
                ('banner', models.ImageField(upload_to='media/', verbose_name='عکس دوره')),
                ('course_type', models.CharField(choices=[('book', 'کتاب'), ('teacher', 'آموزش')], max_length=30, verbose_name='نوع دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
    ]
