# Generated by Django 5.0.6 on 2024-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(default=True, upload_to='media/', verbose_name='عکس دوره'),
        ),
    ]
