# Generated by Django 5.0.6 on 2024-06-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_starter',
            field=models.DateField(help_text='اگر روز شروع خاصی مد نظرتون نیست یا شروع خاصی ندارد تاریخ امروز را وارد کنید', verbose_name='روز شروع دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(help_text='حتما قیمت دوره را به تومان و بدون هیچ علائم نگارشی اضافه ای وارد کنید ', max_length=20, verbose_name='قیمت دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(help_text='فقط اسم و فامیل استاد را بنویسید نیاز به نوشتن کلمه استاد قبل از اسم اساتید نیست ', max_length=30, verbose_name='استاد دوره'),
        ),
    ]
