# Generated by Django 5.0.6 on 2024-06-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_date_starter_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(upload_to='media/', verbose_name='عکس دوره'),
        ),
    ]
