# Generated by Django 5.0.6 on 2024-06-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_off_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_with_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف '),
        ),
    ]
