# Generated by Django 5.0.6 on 2024-06-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_price_with_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='off',
            field=models.IntegerField(blank=True, help_text='لطفا فقط عدد وارد کنید،لطفا عدد وارد شده بین 1 تا 100 باشد', null=True, verbose_name='درصد تخفیف'),
        ),
    ]
