# Generated by Django 5.0.6 on 2024-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='عکس دوره'),
        ),
    ]
