# Generated by Django 5.0.6 on 2024-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='عکس دوره'),
        ),
    ]
