# Generated by Django 5.0.6 on 2025-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='course_banners/', verbose_name='عکس دوره'),
        ),
    ]
