# Generated by Django 5.0.6 on 2024-06-04 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'سبد خرید کاربر', 'verbose_name_plural': 'سبد خرید کاربران'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='banner',
            field=models.ImageField(upload_to='media', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basket',
            name='course_name',
            field=models.CharField(max_length=40, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.CharField(max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basket',
            name='teacher',
            field=models.CharField(max_length=40, verbose_name=''),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='روز خرید شده دوره')),
                ('course_name', models.CharField(max_length=30, verbose_name='نام دوره')),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('baghimande', models.CharField(max_length=20, verbose_name='قیمت باقی مانده')),
                ('pardakhtshode', models.CharField(max_length=20, verbose_name='پرداخت شده')),
                ('course_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='خریدار دوره')),
            ],
            options={
                'verbose_name': 'دوره های کاربر',
                'verbose_name_plural': 'دوره های کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(max_length=20, verbose_name='پرداخت شده')),
                ('status', models.CharField(choices=[('Full', 'تکمیل شده'), ('Not Full', 'تکمیل نشده است')], max_length=50, verbose_name='وضعیت پراخت')),
                ('baghimande', models.CharField(max_length=50, verbose_name='باقی مانده از دوره')),
                ('item_name', models.CharField(max_length=30, verbose_name='نام آیتم')),
                ('date_pay', models.DateField(auto_now_add=True)),
                ('transaction_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ارتباط با')),
            ],
            options={
                'verbose_name': 'پرداخت های اخیر کاربر',
                'verbose_name_plural': 'پرداخت های اخیر کاربران',
            },
        ),
    ]
