# Generated by Django 5.0.6 on 2024-06-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_basket_options_alter_basket_banner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='banner',
            field=models.ImageField(upload_to='media', verbose_name='عکس دوره'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ارتباط با'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='course_name',
            field=models.CharField(max_length=40, verbose_name='نام آیتم'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.CharField(max_length=20, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='teacher',
            field=models.CharField(max_length=40, verbose_name='استاد'),
        ),
    ]
