# Generated by Django 5.0.6 on 2024-06-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_basket_banner_alter_basket_basket_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price_with_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف '),
        ),
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
