# Generated by Django 5.0.6 on 2024-06-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_basket_price_with_off_alter_basket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
