# Generated by Django 5.0.6 on 2024-06-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_remove_basket_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='banner',
        ),
    ]
