# Generated by Django 5.0.6 on 2024-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_remove_basket_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='status',
            field=models.CharField(choices=[('Full', 'تکمیل شده'), ('Not Full', 'تکمیل نشده')], max_length=50, verbose_name='وضعیت پراخت'),
        ),
    ]
