# Generated by Django 5.0.6 on 2024-06-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0028_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس کاربر')),
                ('name', models.CharField(max_length=30, verbose_name='نام کاربر')),
                ('extra_information', models.CharField(blank=True, max_length=50, null=True, verbose_name='اطلاعات بیشتر از کاربر')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن')),
                ('user_student_connect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_to_us', to='account.userstudent')),
            ],
            options={
                'verbose_name': 'ارتباط کاربر ها با مدیرمدرسه',
                'verbose_name_plural': 'ارتباط کاربر ها با مدیرمدرسه',
            },
        ),
    ]
