# Generated by Django 5.0.6 on 2024-06-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_starter',
            field=models.DateField(verbose_name='روز شروع دوره'),
        ),
    ]
