# Generated by Django 5.0.6 on 2024-06-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_course_date_starter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
